services:
  - type: web
    name: mytrading-backend
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
