services:
  - type: web
    name: mytrading-backend
    runtime: python
    buildCommand: |
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
